name: Build and Release APK
on: push
jobs:
    hosting:
      name: Deploy Website
      runs-on: ubuntu-latest
      steps:
        # Checkout Repository
        - uses: actions/checkout@v1

        # Install Flutter command
        - uses: subosito/flutter-action@v1
          with:
            channel: 'dev'

        # Build Website
        - name: Build Website
          run: |
            flutter config --enable-web
            flutter build web

        # Deploy Firebase Hosting
        #- name: Deploy Firebase Hosting
        #  uses: w9jds/firebase-action@master
        #  with:
         #   args: deploy --only hosting:flutter-webhost
         # env:
         #   FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          #  PROJECT_PATH: ./build/web
        - name: creating container
          uses: docker/setup-buildx-action@v1
        - name: docker image build
          uses: docker/login-action@v1
          env:
              GIT_USER: ${{ github.actor}}
              GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
           registry: ghcr.io
           username: $env.GIT_USER
           password: ${{ env.GIT_TOKEN }}
        #- name: build & publis docker image
         # uses: docker/build-push-action@v2
          #env: 
           #   REGISTRY: ghcr.io
         # with:
          # context: .
          # file: ./Dockerfile
          # push: true
          # tags: ${{ env.REGISTRY }}/flutter:1
        - name: build image
          run:
            docker build -t flutter:latest .
        - name: listing images
          run: 
             docker images
        - name: publis image
          run:
            docker push flutter:latest
